apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-pass: {{ .Values.secrets.dbPassword }}
  rmq-pass: {{ .Values.secrets.rmqPassword }}
