# rprofile-dev-app.yaml — AUTO-SYNC
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rprofile-dev
  namespace: argocd
spec:
  project: rprofile-dev
  source:
    repoURL: git@github.com:Raghvendra38/rprofile-helm.git
    targetRevision: main
    path: helm/rprofile-chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rprofile-dev
  syncPolicy:
    automated: # AUTO-SYNC ENABLED
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true